### PR TITLE
sticker-{server,tag}: measure tagging speed

### PR DESCRIPTION
**Pull request by danieldk**
Prints a line to stderr with the tagging speed. For example:

~~~
Processed 9560 sentences in 22.3s (428.0 sents/s)
~~~

### CODE REVIEW

**Comment by sebpuetz** [comment]
Rust 1.31 doesn't like this PR:

```
error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
   --> sticker-utils/src/progress.rs:105:48
    |
105 |             (self.n_sentences as f32 / elapsed.as_millis() as f32) * 1000f32
    |                                                ^^^^^^^^^
                                                                                
error: aborting due to previous error
                                                                                
For more information about this error, try `rustc --explain E0658`.
error: Could not compile `sticker-utils`.
To learn more, run the command again with --verbose.
The command "ci/script.sh" exited with 101.
```

**Comment by danieldk** [comment]
> Rust 1.31 doesn't like this PR:
> 
> ```
> error[E0658]: use of unstable library feature 'duration_as_u128' (see issue #50202)
>    --> sticker-utils/src/progress.rs:105:48
>     |
> 105 |             (self.n_sentences as f32 / elapsed.as_millis() as f32) * 1000f32
>     |                                                ^^^^^^^^^
>                                                                                 
> error: aborting due to previous error
>                                                                                 
> For more information about this error, try `rustc --explain E0658`.
> error: Could not compile `sticker-utils`.
> To learn more, run the command again with --verbose.
> The command "ci/script.sh" exited with 101.
> ```

Indeed, didn't notice the 1.33.0 marker in rustdoc.

**Comment by danieldk** [comment]
> Indeed, didn't notice the 1.33.0 marker in rustdoc.

It's also interesting that `from_millis` takes `u64`, but `as_millis` is `u128`

**Comment by sebpuetz** [comment]
```Rust
            let dur = Instant::now().elapsed();
            let seconds = dur.as_secs();
            let milliseconds = dur.subsec_millis();
            seconds as f32 + milliseconds as f32 / 1000 as f32;
```

This hack might work?

**Comment by danieldk** [comment]
> ```rust
>             let dur = Instant::now().elapsed();
>             let seconds = dur.as_secs();
>             let milliseconds = dur.subsec_millis();
>             secs as f32 + milliseconds as f32 / 1000
> ```
> 
> This hack might work?

Yep. I was just thinking of stealing this:

https://doc.rust-lang.org/src/core/time.rs.html#534-536

**Comment by danieldk** [comment]
Let's see if CI is happy now...

**Pull request merged**
