### PR TITLE
Split Tagger into Tagger and Trainer data structures

### PR DESCRIPTION
**Pull request by danieldk**
This reduces the dependency burden for training uses, since no labels
and vectorizer are needed.

### CODE REVIEW

**Review by sebpuetz — APPROVED** [review]
Looks fine, but I think `TaggerGraph` is not a very clear name for something used both in `Trainer` and `Tagger`. Also, the module `tagger` both holding the `Trainer` and `Tagger` seems odd.

**Comment by danieldk** [comment]
> Looks fine, but I think `TaggerGraph` is not a very clear name for something used both in `Trainer` and `Tagger`. Also, the module `tagger` both holding the `Trainer` and `Tagger` seems odd.

Good points, I'll reshuffle them in the future.

**Comment by danieldk** [comment]
> Good points, I'll reshuffle them in the future.

Maybe `Trainer` should be renamed to `TaggerTrainer`? That would explain the relations between the pieces better.

**Comment by sebpuetz** [comment]
Sounds okay

**Pull request merged**
