### PR TITLE
CI: Test graph writing scripts

### PR DESCRIPTION
**Pull request by danieldk**

### CODE REVIEW

**Comment by danieldk** [comment]
@twuebi let me know if we should add some parameters to the tranformer model that we always want to test to work.

**Comment by twuebi** [comment]
~~~sh
sticker-write-transformer-graph ../shapes g --outer_hsize 350 --pass_inputs --num_heads 7
sticker-write-transformer-graph ../shapes g --outer_hsize 350 --pass_inputs --num_heads 7 --embed_time --max_time 150
~~~

Either the second or both of them would be good #91

**Comment by danieldk** [comment]
Ok, added these tests and rebased on #91.

**Comment by twuebi** [comment]
Gah, forgot the most common use-case:

~~~sh
sticker-write-transformer-graph shapes trans-default.graph
~~~

**Comment by danieldk** [comment]
Added

**Review by twuebi — APPROVED** [review]

**Pull request merged**
